## ----------------------------------------
##  Brewfile
## ----------------------------------------

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
cask_args appdir: "/Applications"

## ========== Common ==========
brew "bat"
brew "cloc"
brew "coreutils"
brew "eza"
brew "fzf"
brew "gnu-sed"
brew "jdx/tap/usage"
brew "jq"
brew "ripgrep"
brew "sl"
brew "direnv"
brew "terminal-notifier"
brew "tree"
brew "mas"
brew "watchman"
brew "wget"
brew "yq"
brew "zoxide"

## ========== Shell ===========
brew "starship"
brew "zsh-completions"
cask "wezterm"

## ========== Fonts ==========
tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"
cask "font-hackgen"
cask "font-hackgen-nerd"

## ========= Utility ==========
tap "1password/tap"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "alt-tab"
cask "cleanshot"
cask "deepl"
cask "hammerspoon"
cask "karabiner-elements"
cask "keycastr"
cask "monitorcontrol"
cask "obsidian"
cask "raycast"

## ========= Browser ==========
cask "arc"
cask "firefox"
cask "google-chrome"

## ======= Development ========
brew "ast-grep"
cask "android-studio"
cask "android-sdk"
cask "android-platform-tools"
brew "cocoapods"
brew "diff-so-fancy"
brew "docker"
brew "git"
brew "git-delta"
brew "gh"
brew "ghq"
cask "google-cloud-sdk"
brew "lazygit"

### ---------- Lang -----------
brew "mise"
brew "openjdk"
brew "php"
brew "python"
brew "rust"
brew "rustup-init"
brew "sbt"
cask "temurin"

### ------- IDE/Editor --------
brew "neovim"
cask "intellij-idea"
cask "visual-studio-code"

### ------- Other Apps --------
cask "postman"

## ======== Quick Look ========
cask "apparency"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "suspicious-package"

# Others
mas "Display Menu", id: 549083868
mas "Hidden Bar", id: 1452453066
mas "Klack", id: 6446206067
mas "Xcode", id: 497799835
