_G.local_config = {
  lsp = {
    biome = { enabled = nil },
    ["css-lsp"] = { enabled = nil },
    css_variables = { enabled = nil },
    cssmodules_ls = { enabled = nil },
    cspell = { enabled = false },
    denols = { enabled = true },
    elmls = { enabled = nil },
    eslint = { enabled = nil },
    gopls = { enabled = nil },
    html = { enabled = nil },
    jsonls = { enabled = nil },
    lua_ls = { enabled = true },
    rust_analyzer = { enabled = nil },
    stylelint_lsp = { enabled = nil },
    svelte = { enabled = nil },
    tailwindcss = { enabled = nil },
    terraformls = { enabled = nil },
    tflint = { enabled = nil },
    ts_ls = { enabled = false },
    yamlls = { enabled = nil },
  },
  formatter = {
    prettier = { enabled = nil },
  },
}
