# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ['defer']

[plugins.fast-syntax-highlighting]
github = 'zdharma/fast-syntax-highlighting'
apply = ['defer']

[plugins.zsh-abbr]
github = 'olets/zsh-abbr'
apply = ['defer']

[plugins.evalcache]
github = 'mroth/evalcache'
apply = ['source']

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
