# nvim 内では nvr を使用して編集対象のファイルを開けるようにしたいので、専用の設定を用意する
# lazygit を立ち上げるときに追加でこのファイルを読み込むことで一部の設定のみを上書きできる
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#overriding-default-config-file-location

os:
  # editPreset: "nvim-remote" # https://github.com/jesseduffield/lazygit/blob/cb1b13e95e09232cced846d167dae6cb21ba696e/pkg/config/editor_presets.go#L54
  edit: nvr --servername "$NVIM" -l -s --remote {{filename}}
  editAtLine: nvr --servername "$NAME" -l -s -c {{line}} --remote {{filename}}
  editAtLineAndWait: nvim +{{line}} {{filename}}
  openDirInEditor: 'nvr --servername "$NVIM" -l -s --remote {{dir}}'
  editInTerminal: false # nvim 内だけの使用ならfalse の方が良い
