[tools]
# nixpkgs にないため mise で管理

## LSP
"npm:css-variables-language-server" = "2.8.4"
"npm:cssmodules-language-server" = "1.5.2"

## CLI
"cargo:https://github.com/skanehira/version-lsp.git" = "latest"
"github:ushironoko/abbrs" = "0.2.10"
"github:Warashi/cage" = "0.1.13"
