vim.api.nvim_create_user_command("CopyRelativePath", function()
  local path = vim.fn.expand("%:.")
  vim.api.nvim_out_write("Copied: " .. path .. "\n")
  vim.fn.setreg("+", path)
end, {})
vim.api.nvim_create_user_command("CopyFullPath", function()
  local path = vim.fn.expand("%:p")
  vim.api.nvim_out_write("Copied: " .. path .. "\n")
  vim.fn.setreg("+", path)
end, {})
vim.api.nvim_create_user_command("CopyFileName", function()
  local path = vim.fn.expand("%:t")
  vim.api.nvim_out_write("Copied: " .. path .. "\n")
  vim.fn.setreg("+", path)
end, {})
vim.api.nvim_create_user_command("CopyGithubLink", function()
  -- 現在の行のリンクをコピー
  local file = vim.fn.expand("%:.")
  local line = vim.fn.line(".")
  local url = vim.fn.system("gh browse -n '" .. file .. ":" .. line .. "'")
  vim.api.nvim_out_write("Copied: " .. url)
  vim.fn.setreg("+", url)
end, {})
vim.api.nvim_create_user_command("CopyGithubFileLink", function()
  -- 現在のファイルのリンクをコピー
  local file = vim.fn.expand("%:.")
  local url = vim.fn.system("gh browse -n '" .. file .. "'")
  vim.api.nvim_out_write("Copied: " .. url)
  vim.fn.setreg("+", url)
end, {})
