-- Key Binding (Pluginは除く)
vim.keymap.set('i', '<C-a>', '<C-o>^', {})
vim.keymap.set({'n', 'v'}, '<C-a>', '^', {})
vim.keymap.set('i', '<C-e>', '<C-o>$', {})
vim.keymap.set({'n', 'v'}, '<C-e>', '$', {})
vim.keymap.set('n', '<C-S-h>', '<cmd>wincmd h<CR>', {})
vim.keymap.set('n', '<C-S-l>', '<cmd>wincmd l<CR>', {})
vim.keymap.set('n', '<C-S-j>', '<cmd>wincmd j<CR>', {})
vim.keymap.set('n', '<C-S-k>', '<cmd>wincmd k<CR>', {})
