# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
git:
  paging:
    colorArg: always
    # externalDiffCommand: difft --color=always
gui:
  showIcons: true
  sidePanelWidth: 0.25
  language: "en"
  timeFormat: "2006-01-02T15:04:05Z07:00" # '02 Jan 06 15:04 MST' # https://pkg.go.dev/time#Time.Format
  commandLogSize: 16

# https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md
customCommands:
  - key: null
    command: "gh repo view -w"
    context: "global"
    loadingText: "view repo on GitHub"
  - key: "<c-r>"
    command: "gh pr view {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    description: "view pull request"
    subprocess: true
  - key: "C"
    context: "files"
    command: "git commit -v -t ~/.config/git/commit_template_with_prompt.txt"
    description: "Commit changes using git editor"
    subprocess: true
  - key: null
    command: "gh pr merge {{.SelectedLocalBranch.Name}} -d {{index .PromptResponses 0}}"
    context: "localBranches"
    description: "merge pull request"
    prompts:
      - type: "menu"
        title: "Select merge option"
        options:
          - value: "--merge"
            name: "Create a merge commit"
            description: "gh pr merge {{.SelectedLocalBranch.Name}} -d --merge -b ''"
          - value: "--squash"
            name: "Squash and merge"
            description: "gh pr merge {{.SelectedLocalBranch.Name}} -d --squash -b ''"
          - value: "--rebase"
            name: "Rebase and merge"
            description: "gh pr merge {{.SelectedLocalBranch.Name}} -d --rebase -b ''"
keybinding:
  universal:
    openRecentRepos: null # '<c-r>'
    commitChangesWithEditor: null # 'C'
