# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  showIcons: true
  language: 'en'
  timeFormat: '2006-01-02T15:04:05Z07:00' # '02 Jan 06 15:04 MST' # https://pkg.go.dev/time#Time.Format
customCommands:
  - key: '<c-r>'
    command: 'gh repo view -w'
    context: 'global'
    loadingText: 'View repo on GitHub'
keybinding:
  universal:
    openRecentRepos: null # '<c-r>'
