# ~/.config/starship.toml
# https://starship.rs/ja-jp/config/

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$custom\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

command_timeout = 1000

[aws]
symbol = " "

[battery]
format = "[$symbol$percentage]($style) "

[conda]
symbol = " "

[character]
success_symbol = "[>](bold green) "
error_symbol = "[✗](bold red) "

[cmd_duration]
min_time = 10
format = "[\\[$duration\\]](yellow)"
show_notifications = true

[dart]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[deno]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = "🦕"

[directory]
truncation_length = 5
truncation_symbol = "…/"
read_only = " "

[docker_context]
symbol = " "

[elixir]
version_format = "v${major}.${minor}"
symbol = " "

[elm]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = ""

[gcloud]
format = "[$symbol$active]($style) "
style = "bold yellow"
symbol = " " # \ue7b2

[git_branch]
format = "[$symbol$branch]($style) "
truncation_length = 32
truncation_symbol = "…"
symbol = ""

[golang]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[hg_branch]
symbol = " "

[java]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[julia]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[kotlin]
version_format = "v${major}.${minor}"
symbol = "🅺 "

[memory_usage]
# format = "$symbol [${ram}( \\| ${swap})]($style) "
symbol = " "
disabled = false

[nim]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[package]
format = "[<$symbol$version>]($style) "
version_format = "v${major}.${minor}"
symbol = " "
disabled = true

[perl]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[php]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[python]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[ruby]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[rust]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[scala]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = " "

[shlvl]
symbol = " "

[swift]
format = "[$symbol($version)]($style) "
version_format = "v${major}.${minor}"
symbol = "ﯣ "

[custom.unipos]
command = """echo "GAE_PROJECT=$GAE_PROJECT, UNIPOS_ENV=$UNIPOS_ENV" """
format = "\n[$output]($style) "
when = """string match '*unipos*' $PWD"""
style = "#cfcfcf"
