[[abbr]]
keyword = "g"
expansion = "git"

[[abbr]]
keyword = "cm"
expansion = "chezmoi"

[[abbr]]
keyword = "lg"
expansion = "lazygit"

[[abbr]]
keyword = "t"
expansion = "trev"

[[abbr]]
keyword = "cl"
expansion = "claude"

[[abbr]]
keyword = "pn"
expansion = "pnpm"

[[abbr]]
keyword = "ls"
expansion = "lsd"
allow_conflict = true

[[abbr]]
keyword = "la"
expansion = "lsd -a"

[[abbr]]
keyword = "ll"
expansion = "lsd -la"

[[abbr]]
keyword = "icat"
expansion = "chafa"

[[abbr]]
keyword = "docker-compose"
expansion = "docker compose"

[[abbr]]
keyword = "Rmdsstore"
expansion = 'find . -name ".DS_Store" -type f -ls -delete'
allow_conflict = true

[[abbr]]
keyword = "head"
expansion = "ghead"
global = true
allow_conflict = true

[[abbr]]
keyword = "tail"
expansion = "gtail"
global = true
allow_conflict = true

[[abbr]]
keyword = "sed"
expansion = "gsed"
global = true
allow_conflict = true

[[abbr]]
keyword = "co"
expansion = "checkout"
command = "git"

[[abbr]]
keyword = "cp"
expansion = "cherry-pick"
command = "git"
allow_conflict = true
