# herdr configuration
# default config: herdr --default-config
# docs:           https://github.com/ogulcancelik/herdr/blob/master/CONFIGURATION.md

onboarding = false

[theme]
name = "tokyo-night"

[ui.sound]
enabled = true

[ui.toast]
delivery = "terminal"

[keys]
focus_pane_left = "alt+shift+h"
focus_pane_down = "alt+shift+j"
focus_pane_up = "alt+shift+k"
focus_pane_right = "alt+shift+l"
rename_tab = "prefix+shift+c"
previous_tab = ["alt+[", "alt+shift+["]
next_tab = ["alt+]", "alt+shift+]"]
zoom = ["ctrl+shift+enter", "prefix+f"]

[[keys.command]]
key = "prefix+n"
type = "pane"
command = "nvim"

[[keys.command]]
key = "prefix+g"
type = "pane"
command = "lazygit"
