"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 4
final_space = true
async = true
shell_integration = true

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "blue"
  template = "{{ .Path }} "
  [blocks.segments.options]
  style = "folder"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "status"
  style = "plain"
  foreground = "green"
  foreground_templates = ["{{ if .Error }}red{{ end }}"]
  template = "{{ if eq .Code 0 }}>{{ else }}✗{{ end }} "
  [blocks.segments.options]
  always_enabled = true
